require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/holders", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Holder. As you add validations to Holder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Holder.create! valid_attributes
      get holders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      holder = Holder.create! valid_attributes
      get holder_url(holder)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_holder_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      holder = Holder.create! valid_attributes
      get edit_holder_url(holder)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Holder" do
        expect {
          post holders_url, params: { holder: valid_attributes }
        }.to change(Holder, :count).by(1)
      end

      it "redirects to the created holder" do
        post holders_url, params: { holder: valid_attributes }
        expect(response).to redirect_to(holder_url(Holder.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Holder" do
        expect {
          post holders_url, params: { holder: invalid_attributes }
        }.to change(Holder, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post holders_url, params: { holder: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested holder" do
        holder = Holder.create! valid_attributes
        patch holder_url(holder), params: { holder: new_attributes }
        holder.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the holder" do
        holder = Holder.create! valid_attributes
        patch holder_url(holder), params: { holder: new_attributes }
        holder.reload
        expect(response).to redirect_to(holder_url(holder))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        holder = Holder.create! valid_attributes
        patch holder_url(holder), params: { holder: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested holder" do
      holder = Holder.create! valid_attributes
      expect {
        delete holder_url(holder)
      }.to change(Holder, :count).by(-1)
    end

    it "redirects to the holders list" do
      holder = Holder.create! valid_attributes
      delete holder_url(holder)
      expect(response).to redirect_to(holders_url)
    end
  end
end
